### ISSUE TITLE
Bug and Fix

### ISSUE THREAD

**Issue by mindkind** [luischennn/es_doorbell#3]
RegisterNetEvent('es_doorbell:NotifyJob')
AddEventHandler('es_doorbell:NotifyJob', function(job)

	local src = source
    local xPlayers = ESX.GetPlayers()

    for i=1, #xPlayers, 1 do
        local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		
		if src == xPlayer.source then
			TriggerClientEvent('ox_lib:notify', xPlayer.source, {title = Config.Bell, description = Config.YouRang, duration = 5000, position = 'center-left', type = 'success'})
		end
		
        if xPlayer.getJob().name == job and src ~= xPlayer.source then
            TriggerClientEvent('ox_lib:notify', xPlayer.source, {title = Config.Bell, description = Config.SomeoneRang, duration = 5000, position = 'center-left', type = 'inform'})
        end
    end

end)

**Comment by luischennn** [comment]
code replaced in:

```lua
    local xPlayers = ESX.GetExtendedPlayers('job', pJob)

    for i, xPlayer in ipairs(xPlayers) do
        TriggerClientEvent('ox_lib:notify', xPlayer.source, {title = Config.Bell, description = Config.SomeoneRang, duration = 5000})
    end
```
